// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A flow that answers questions about campus events and activities.
 *
 * - answerCampusQuestions - A function that answers campus-related questions.
 * - AnswerCampusQuestionsInput - The input type for the answerCampusQuestions function.
 * - AnswerCampusQuestionsOutput - The return type for the answerCampusQuestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerCampusQuestionsInputSchema = z.object({
  question: z.string().describe('The question about campus events and activities.'),
});
export type AnswerCampusQuestionsInput = z.infer<typeof AnswerCampusQuestionsInputSchema>;

const AnswerCampusQuestionsOutputSchema = z.object({
  answer: z.string().describe('The answer to the question about campus events and activities.'),
});
export type AnswerCampusQuestionsOutput = z.infer<typeof AnswerCampusQuestionsOutputSchema>;

export async function answerCampusQuestions(input: AnswerCampusQuestionsInput): Promise<AnswerCampusQuestionsOutput> {
  return answerCampusQuestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerCampusQuestionsPrompt',
  input: {schema: AnswerCampusQuestionsInputSchema},
  output: {schema: AnswerCampusQuestionsOutputSchema},
  prompt: `You are a helpful AI assistant that answers questions about campus events and activities.

  Question: {{{question}}}
  Answer: `,
});

const answerCampusQuestionsFlow = ai.defineFlow(
  {
    name: 'answerCampusQuestionsFlow',
    inputSchema: AnswerCampusQuestionsInputSchema,
    outputSchema: AnswerCampusQuestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
